version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dhcp4
      - POSTGRES_DB=dhcp4
    volumes:
      - ./dhcp4/:/var/lib/postgresql/data
