version: '3'
services:
  goworkspace:
    build:
      context: .
      dockerfile: Dockerfile-goworkspace
    entrypoint: /bin/sleep infinity
    restart: unless-stopped
    volumes:
      - ./:/code/src/github.com/Its-Alex/dhcp4-reservation

  postgres:
    image: postgres:9.6-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dhcp4
      - POSTGRES_PASSWORD=dhcp4
      - POSTGRES_DB=dhcp4
    volumes:
      - ./data-dhcp4/:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
